services:
  multi-agent-chatbot:
    build: ./
    container_name: multi-agent-chatbot
    ports:
      - "8000:8000"
    volumes:
      - database_volume:/multi-agent-chatbot/application_db
      - app_logs_volume:/multi-agent-chatbot/application_logs
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
volumes:
  database_volume:
  app_logs_volume: